<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="kartheeswari-pc" failures="0" tests="8" name="HospitalPortalFlow.new_Patient_Creation" time="53.618" errors="1" timestamp="2021-03-31T17:49:10 IST" skipped="7">
  <testcase classname="HospitalPortalFlow.new_Patient_Creation" name="launch" time="53.618">
    <error message="org.openqa.selenium.support.ui.WebDriverWait.&lt;init&gt;(Lorg/openqa/selenium/WebDriver;Ljava/time/Duration;)V" type="java.lang.NoSuchMethodError">
      <![CDATA[java.lang.NoSuchMethodError: org.openqa.selenium.support.ui.WebDriverWait.<init>(Lorg/openqa/selenium/WebDriver;Ljava/time/Duration;)V
at HospitalPortalFlow.new_Patient_Creation.launch(new_Patient_Creation.java:124)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:61)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:366)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:320)
at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:617)
at org.testng.TestRunner.beforeRun(TestRunner.java:607)
at org.testng.TestRunner.run(TestRunner.java:578)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- launch -->
  <system-out/>
  <testcase classname="HospitalPortalFlow.new_Patient_Creation" name="fill_data" time="0.000">
    <skipped/>
  </testcase> <!-- fill_data -->
  <system-out/>
  <testcase classname="HospitalPortalFlow.new_Patient_Creation" name="fill_data" time="0.000">
    <skipped/>
  </testcase> <!-- fill_data -->
  <system-out/>
  <testcase classname="HospitalPortalFlow.new_Patient_Creation" name="fill_data" time="0.000">
    <skipped/>
  </testcase> <!-- fill_data -->
  <system-out/>
  <testcase classname="HospitalPortalFlow.new_Patient_Creation" name="fill_data" time="0.000">
    <skipped/>
  </testcase> <!-- fill_data -->
  <system-out/>
  <testcase classname="HospitalPortalFlow.new_Patient_Creation" name="fill_data" time="0.000">
    <skipped/>
  </testcase> <!-- fill_data -->
  <system-out/>
  <testcase classname="HospitalPortalFlow.new_Patient_Creation" name="fill_data" time="0.000">
    <skipped/>
  </testcase> <!-- fill_data -->
  <system-out/>
  <testcase classname="HospitalPortalFlow.new_Patient_Creation" name="fill_data" time="0.000">
    <skipped/>
  </testcase> <!-- fill_data -->
  <system-out/>
</testsuite> <!-- HospitalPortalFlow.new_Patient_Creation -->
